[project]
name = "ems-wrapper"
version = "0.4.1"
description = "ML pipelines for EMS-Copilot: development and deployment"
readme = "README.md"
requires-python = ">=3.7,<3.10"
dependencies = [
    "tensorflow==2.8.0",
]

[tool.uvicorn.reload]
exclude = ["test/**"]

[dependency-groups]
dev = [
    "ipykernel>=6.16.2",
    "notebook>=6.5.7",
    "ruff>=0.14.1",
]
container = [
    "tensorflow-addons==0.16.1",
    "fastapi>=0.103.2",
    "uvicorn>=0.22.0",
    "gunicorn>=23.0.0",
    "struct2tensor>=0.39.0",

]
routine = [
    "google-cloud-aiplatform[prediction]"
]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]