[project]
name = "ems-wrapper"
version = "0.3.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7,<3.10"
dependencies = [
    "tensorflow==2.8.0",
    "tensorflow-addons==0.16.1",
    "protobuf<=3.20.3",
    "numpy<=1.21.6",
    "fastapi>=0.103.2",
    "uvicorn>=0.22.0",
    "gunicorn>=23.0.0",
    "struct2tensor>=0.39.0",
    "pandas>=1.1.5",
]

[tool.uvicorn.reload]
exclude = ["test/**"]
